
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONCEPTOS_BUSQUEDAS` (
  `id_busquedas` INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL,
  `concepto` VARCHAR(100) NULL) ;

CREATE TABLE IF NOT EXISTS `DATOS` (
  `id_leyes` INTEGER PRIMARY KEY  AUTOINCREMENT NOT NULL,
  `documento` VARCHAR(3) NOT NULL,
  `bandera_Vista` INT(1)  NOT NULL,
  `noArticulo` VARCHAR(100) NOT NULL
  ) ;
CREATE TABLE IF NOT EXISTS `ContenidoDatos`(
  `FK_id_leyes` VARCHAR(6) NOT NULL CONSTRAINT FK_id_leyes REFERENCES DATOS(id_leyes) ON DELETE CASCADE,
  `contenido` TEXT NOT NULL
) ;
CREATE TABLE IF NOT EXISTS `DATOS_CONCEPTOBUSQUEDA` (
  `FK_id_busqueda` INTEGER NOT NULL CONSTRAINT FK_id_busqueda REFERENCES CONCEPTOS_BUSQUEDAS(id_busquedas) ON DELETE CASCADE,
  `FK_id_leyes` VARCHAR(6) NOT NULL CONSTRAINT FK_id_leyes REFERENCES DATOS(id_leyes) ON DELETE CASCADE
); 



---------------------------------------------------------------
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Ninguno');
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Becas');
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Calidad de Vida');
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Capacitación y adiestramiento'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Certificación del   Trabajador'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Comisiones Mixtas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Comisiones Mixtas Únicas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Conflicto colectivo de naturaleza económica'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consecuencias para el sindicato el incumplimiento'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consecuencias para el trabajador el incumplimiento'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consecuencias para la empresa el incumplimiento'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consecuencias para la empresa el incumplimiento de pago'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Contrato Colectivo de Trabajo'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Contrato ley'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consejos Mixtos Nacional de Modernización'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consejos Mixtos Locales de Modernización'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Consejo Nacional contra las Adicciones'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Condiciones que más favorezcan al trabajador'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Cubrimientos de vacantes'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Definiciones de Ley'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Definiciones del Contrato Ley'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Derechos de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Derecho de los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Derecho del Sindicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Derecho de los familiares'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Diálogo social'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Días de descanso'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Disciplina'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Dotación de herramientas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Educación Básica'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Estímulo económico'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación permanente, obligaciones bilaterales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación permanente, obligaciones de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación permanente, obligaciones del sidicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación permanente, obligaciones de los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación permanente, obligaciones de la Comisión Mixta Única'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación permanente, obligaciones del Consejo Mixto Local'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación por competencias, obligaciones bilaterales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación por competencias, obligaciones de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación por competencias, obligaciones del sidicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación por competencias, obligaciones de los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación a eventuales preferentes, obligaciones bilaterales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación a eventuales preferentes, obligaciones de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación a eventuales preferentes, obligaciones del sindicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formación a eventuales preferentes, obligaciones de los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Formas específicas de pago'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Garantías individuales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Huelga'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Jornada de trabajo'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Jubilaciones'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Movilidad del personal'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones bilaterales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones de los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones del sindicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones de la empresa de informar o entregar'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones del sindicato de informar o entregar'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Obligaciones de pago de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Optimización de Recursos Humanos'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Prescripción'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Productividad y Calidad'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Rentabilidad y Sostenibilidad de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Prohibiciones a la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Prohibiciones a los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Prohibiciones al sindicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Reconocimiento de las partes'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Reparto de Utilidades'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Relaciones colectivas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Reglamento Interior de Trabajo'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salario'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, Normas Oficiales Mexicana'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, obligaciones bilaterales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, obligaciones de la empresa'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, obligaciones del sidicato'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, obligaciones de los trabajadores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, obligaciones del Consejo Mixto Nacional'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Salud, Seguridad, Higiene y Medio Ambiente, obligaciones del Consejo Mixtos Locales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Sindicato, relaciones colectivas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Suspensión colectiva de las relaciones de trabajo'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Terminación colectiva de las relaciones de trabajo'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajadores de confianza'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajadores de nuevo ingreso, requisitos'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos insalubres, peligrosos'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, en el campo'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, en los buques'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo a domicilio'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, autotransporte'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, de comercio y otros semejantes'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo de las mujeres'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo de tripulaciones aereonáuticas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo de los menores'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, maniobras de servicio público, jurisdicción federal'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo de los médicos'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo doméstico'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo en hoteles, restaurantes, bares y otros.'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo en industria familiar.'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo en universidades'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo en minas'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo ferrocarrilero'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo de actores y música'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Trabajos especiales, trabajo de deportistas profesionales'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Vacaciones'); 
INSERT INTO CONCEPTOS_BUSQUEDAS (id_busquedas,concepto) VALUES(?,'Vivienda');

INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO PRIMERO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO SEGUNDO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO TERCERO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO CUARTO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO QUINTO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO EXTO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO SEPTIMO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO OCTAVO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO NOVENO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO DECIMO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO DECIMO PRIMERO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO DECIMO SEGUNDO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'ACM',0,'ACUERDO DECIMO TERCERO');


INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 5o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” PRIMER PÁRRAFO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN I');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN II');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN III');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IV');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN V');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN VI');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN VII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN VIII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX PRIMER PÁRRAFO');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX INCISO A)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX INCISO B)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX INCISO C)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX INCISO D)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX INCISO E)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN IX INCISO F)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN X');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XI');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XIII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XIV');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XV');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XVI');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XVII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XVIII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XIX');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XX');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXI');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXIII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXIV');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXV');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVI');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO A)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO B)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO C)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO D)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO E)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO F)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO G)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVII INCISO H)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXVIII');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXIX');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXX');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXXI INCISO A)');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'CON',0,'ARTÍCULO 123. APARTADO “A” FRACCIÓN XXXI INCISO B)');

INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 1o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 2o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 3o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 4o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 6o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 7o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 8o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 9o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 10');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 11');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 12');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 13');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 14');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 15');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 16');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 17');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 18');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 19');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 20');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 21');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 22');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 23');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 24');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 25');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 26');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 27');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 28');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 29');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 30');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 31');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 32');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 33');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 34');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 35');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 36');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 37');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 38');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 39');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 40');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 41');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 42');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 43');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 44');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 46');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 47');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 54');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 56');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 57');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 58');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 59');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 60');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 61');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 61 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 62');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 63');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 64');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 65');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 66');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 67');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 68');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 69');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 70');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 71');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 71 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 72');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 73');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 74');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 75');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 76');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 77');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 78');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 79');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 80');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 81');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 82');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 83');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 84');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 85');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 86');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 87');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 88');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 89');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 90');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 91');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 92');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 93');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 94');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 95');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 96');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 97');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 98');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 99');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 100');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 101');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 102');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 103');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 104');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 105');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 106');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 107');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 108');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 109');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'COL',0,'ARTÍCULO 110');

INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 1o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 2o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 3o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 3o Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 4o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 5o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 6o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 7o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 8o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 9o');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 10');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 11');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 12');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 13');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 14');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 15');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 15-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 15-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 15-C');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 15-D');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 16');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 17');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 18');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 19');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 20');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 21');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 22');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 22 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 23');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 24');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 25');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 26');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 27');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 28');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 28-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 28-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 29');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 30');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 31');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 32');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 33');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 34');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 35');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 36');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 37');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 38');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39-C');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39-D');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39-E');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 39-F');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 40');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 41');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 42');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 42 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 43');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 44');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 45');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 46');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 47');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 48');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 49');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 50');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 51');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 52');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 53');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 54');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 55');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 56');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 56 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 57');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 58');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 59');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 60');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 61');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 62');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 63');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 64');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 65');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 66');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 67');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 68');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 69');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 70');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 71');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 72');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 73');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 74');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 75');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 76');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 77');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 78');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 79');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 80');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 81');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 82');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 83');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 84');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 85');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 86');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 87');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 88');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 89');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 90');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 91');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 92');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 93');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 94');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 95');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 96');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 97');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 98');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 99');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 100');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 101');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 102');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 103');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 103 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 104');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 105');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 106');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 107');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 108');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 109');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 110');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 111');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 112');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 113');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 114');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 115');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 116');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 117');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 118');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 119');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 120');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 121');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 122');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 123');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 124');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 125');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 126');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 127');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 128');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 129');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 130');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 131');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 132');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 133');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 134');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 135');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 136');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 137');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 138');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 139');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 140');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 141');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 142');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 143');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 144');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 145');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 146');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 147');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 148');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 149');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 150');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 151');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 152');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-C');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-D');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-E');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-F');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-F Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-G');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-H');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-I');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-J');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-K');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-L');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-M');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-N');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-Q');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-S');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-T');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-U');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-V');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-W');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 153-X');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 154');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 155');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 156');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 157');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 158');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 159');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 160');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 161');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 162');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 163');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 164');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 165');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 166');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 167');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 168');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 169');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 170');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 171');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 172');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 173');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 174');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 175');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 175 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 176');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 177');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 178');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 179');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 180');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 181');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 182');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 183');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 184');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 185');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 186');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 187');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 188');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 189');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 190');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 191');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 192');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 193');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 194');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 195');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 196');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 197');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 198');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 199');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 200');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 201');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 202');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 203');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 204');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 205');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 206');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 207');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 208');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 209');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 210');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 211');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 212');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 213');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 214');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 215');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 216');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 217');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 218');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 219');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 220');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 221');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 222');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 223');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 224');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 225');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 226');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 227');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 228');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 229');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 230');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 231');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 232');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 233');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 234');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 235');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 236');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 237');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 238');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 239');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 240');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 241');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 242');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 243');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 244');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 245');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 246');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 247');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 248');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 249');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 250');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 251');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 252');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 253');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 254');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 255');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 256');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 257');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 258');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 259');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 260');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 261');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 262');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 263');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 264');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 265');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 266');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 267');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 268');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 269');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 270');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 271');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 272');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 273');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 274');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 275');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 276');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 277');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 278');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 279');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 279 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 279 Ter');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 280');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 281');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 282');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 283');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 284');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 285');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 286');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 287');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 288');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 289');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 290');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 291');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 292');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 293');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 294');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 295');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 296');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 297');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 298');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 299');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 300');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 301');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 302');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 303');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 304');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 305');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 306');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 307');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 308');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 309');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 310');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 311');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 312');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 313');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 314');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 315');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 316');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 317');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 318');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 319');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 320');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 321');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 322');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 323');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 324');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 325');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 326');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 327');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 328');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 329');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 330');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 331');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 332');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 333');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 334');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 335');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 336');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 337');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 338');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 339');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 340');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 341');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 342');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 343');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 343-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 343-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 343-C');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 343-D');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 343-E');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 344');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 345');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 346');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 347');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 348');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 349');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 350');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 351');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 352');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-C');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-D');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-E');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-F');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-G');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-I');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-J');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-K');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-L');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-M');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-N');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-Ñ');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-O');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-P');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-Q');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-R');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-S');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-T');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 353-U');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 354');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 355');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 356');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 357');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 358');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 359');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 360');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 361');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 362');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 363');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 364');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 364 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 365');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 365 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 366');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 367');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 368');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 369');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 370');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 371');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 372');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 373');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 374');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 375');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 376');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 377');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 378');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 379');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 380');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 381');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 382');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 383');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 384');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 385');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 386');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 387');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 388');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 389');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 390');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 391');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 391 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 392');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 393');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 394');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 395');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 396');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 397');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 398');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 399');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 399 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 400');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 401');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 402');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 403');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 404');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 405');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 406');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 407');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 408');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 409');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 410');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 411');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 412');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 413');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 414');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 415');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 416');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 417');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 418');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 419');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 419 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 420');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 421');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 422');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 423');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 424');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 424 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 425');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 426');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 427');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 428');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 429');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 430');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 431');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 432');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 433');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 434');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 435');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 436');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 437');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 438');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 439');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 440');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 441');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 442');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 443');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 444');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 445');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 446');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 447');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 448');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 449');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 450');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 451');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 452');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 453');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 454');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 455');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 456');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 457');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 458');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 459');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 460');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 461');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 462');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 463');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 464');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 465');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 466');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 469');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 472');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 473');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 474');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 475');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 475 Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 476');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 477');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 478');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 479');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 480');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 481');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 482');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 483');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 484');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 485');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 486');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 487');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 488');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 489');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 490');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 491');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 492');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 493');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 494');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 495');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 496');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 497');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 498');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 499');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 500');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 501');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 502');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 503');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 504');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 505');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 506');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 507');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 508');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 509');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 510');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 511');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-A');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-B');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-C');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-D');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-D Bis');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-D Ter');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-E');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-F');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 512-G');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 513');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 514');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 515');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 516');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 517');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 518');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 519');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 520');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 521');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'LFT',0,'ARTÍCULO 522');

INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA PRIMERA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA SEGUNDA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA TERCERA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA CUARTA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA QUINTA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA SEXTA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA SEPTIMA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA OCTAVA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA NOVENA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA PRIMERA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA SEGUNDA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA TERCERA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA CUARTA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA QUINTA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA SEXTA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA SEPTIMA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA OCTAVA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA DECIMA NOVENA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA VIGESIMA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA VIGESIMA PRIMERA');
INSERT INTO DATOS (id_leyes,documento,bandera_Vista,noArticulo) VALUES(?,'PLR',0,'CLAUSULA VIGESIMA SEGUNDA');


Select * FROM CONCEPTOS_BUSQUEDAS

Select * FROM DATOS WHERE id_leyes in (
select FK_id_leyes from DATOS_CONCEPTOBUSQUEDA where FK_id_busqueda=1)





